/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGraphique;

import java.awt.GridLayout;
import java.awt.Panel;
import java.awt.TextField;
import java.util.logging.Level;
import java.util.logging.Logger;
import jeugo.Enregistrement;
import jeugo.PlateauDeJeu;
import jeugo.Position;
import jeugo.exceptions.PasDePlateaudeCetteTaille;

/**
 *
 * @author oriane école
 */
public class Goban extends javax.swing.JFrame {

    /**
     * Creates new form Goban2
     */
    public Goban() {
        try {
            //initComponents();
            pl = new PlateauDeJeu(9);
            cases = new Case[19][19];
            int taille = 0;
            tour = true;
        } catch (PasDePlateaudeCetteTaille ex) {
            Logger.getLogger(Goban.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void initCases(int taille){
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menuItem1 = new java.awt.MenuItem();
        menuItem2 = new java.awt.MenuItem();

        menu1.setLabel("Partie");

        menuItem1.setLabel("Sauvegarder");
        menuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SauvegarderActionPerformed(evt);
            }
        });
        menu1.add(menuItem1);

        menuItem2.setLabel("Charger");
        menuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChargerActionPerformed(evt);
            }
        });
        menu1.add(menuItem2);

        menuBar1.add(menu1);
        
        setMenuBar(menuBar1);
        
        mainPanel = new Panel();
        message = new TextField();
        
        message.setEditable(false);
        message.setColumns(25);
 
        panel1 = new Panel();
        GridLayout grille = new GridLayout(taille,taille,0,0);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        panel1.setLayout(grille);
        
        for (int i = 0; i < taille; i++) {
            for (int j = 0; j < taille; j++) {
                cases[i][j] = new Case(i, j);
                cases[i][j].setVisible(true);
                cases[i][j].addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        caseMouseClicked(evt);
                    }
                });
                panel1.add(cases[i][j]);
            }
        }
        panel1.setSize(25*taille, 25*taille);
        
        mainPanel.add(panel1);
        
        mainPanel.add(message);
        setContentPane(mainPanel);
        setSize(27*taille,35*taille);
    }
     
     private void caseMouseClicked(java.awt.event.MouseEvent evt) {
             Position pos = new Position(((Case) evt.getSource()).getPosX(), ((Case) evt.getSource()).getPosY());
             String res = pl.jouer(pos, tour);
             if (res=="ok"){
                 this.updatePlateau();
                 tour =!tour;
                 if (tour){
                 message.setText("C'est au tour du joueur Blanc : "+pl.getjBlanc());
                 } else {
                     message.setText("C'est au tour du joueur Noir : "+pl.getjNoir());
                 }
             } else {
                 message.setText(res);
             }
             
    }
     private void SauvegarderActionPerformed(java.awt.event.ActionEvent evt) {
         // à corriger
         String nomFichier = "test";
         Enregistrement.enregistrer(nomFichier, pl);
     }
     private void ChargerActionPerformed(java.awt.event.ActionEvent evt) {
         // a écrire
     }
     
     private void updatePlateau(){
         for (int i = 0; i < this.pl.getWidth(); i++) {
            for (int j = 0; j < this.pl.getWidth(); j++) {
                if (this.pl.pieces[i][j]!=null){
                    cases[i][j].setAffichage(this.pl.pieces[i][j].getCouleur());
                } else {
                    cases[i][j].setVide();
                }
            }
         }
     }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 266, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Goban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Goban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Goban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Goban.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Goban().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private java.awt.Panel mainPanel;
    private java.awt.Panel panel1;
    private Case[][] cases;
    private PlateauDeJeu pl;
    private boolean tour;
    private java.awt.TextField message;
    
    private java.awt.Menu menu1;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuItem menuItem1;
    private java.awt.MenuItem menuItem2;
    
    public void setPlateauDeJeu(PlateauDeJeu p) throws PasDePlateaudeCetteTaille{
        this.pl=new PlateauDeJeu(p);
    }
    public PlateauDeJeu getPlateauDeJeu(){
        return pl;
    }
}

